# Generated by Django 6.0.6 on 2026-06-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ACL', 'ACL Generator'), ('CURATOR', 'ArtiCurator')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('log_output', models.TextField(blank=True, null=True)),
                ('config_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
