# Generated by Django 6.0.6 on 2026-06-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_prompttemplate_remove_agenttask_log_output_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromptTemplate',
        ),
    ]
