# Generated by Django 6.0.6 on 2026-06-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_delete_prompttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='execution_logs',
            field=models.TextField(default=''),
        ),
    ]
