# web/views.py
import os
import json
import threading
from django.views.decorators.http import require_POST
from django.shortcuts import render, redirect, get_object_or_404
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse
from web.models import AgentTask, PromptTemplate
from modules.orchestrator import execute_agent_task

def select_mode_view(request):
    """Step 1: Choose Operational Mode"""
    if request.method == 'POST':
        mode = request.POST.get('mode', 'ACLGENERATOR')
        return redirect(f'/configure/?mode={mode}')
    return render(request, 'select_mode.html')

def config_form_view(request):
    """Step 2: Inputs, Prompt Layouts, and Agent Model Allocation Matrices"""
    # 1. Strictly isolate mode configuration up front
    mode = request.GET.get('mode', 'ACLGENERATOR')
    load_task_id = request.GET.get('load_task_id', '')
    template_id = request.GET.get('template_id', '')
    
    # If loading from a past task execution context, look up its actual native mode
    if load_task_id:
        try:
            past_task = AgentTask.objects.get(id=load_task_id)
            mode = past_task.mode
        except AgentTask.DoesNotExist:
            pass

    saved_templates = PromptTemplate.objects.filter(description=mode)
    config_context = {}

    # 2. Assign default prompts explicitly based on the validated mode state
    if mode == 'ARTICURATOR':
        prompts = {
            "agent_1": (
                "You are Analisa, a premier research and strategic information discovery agent. "
                "Your objective is to thoroughly investigate the user's provided theme. "
                "Break down the theme into core historical context, vital statistics, key arguments, "
                "and notable perspectives. Your output must be an exhaustive, structured intelligence report "
                "dense with factual data, organized logically with clear topical sections. Do not write "
                "the final article; provide the deep raw knowledge baseline that subsequent agents require."
            ),
            "agent_2": (
                "You are Writus, an elite narrative synthesis engineer and technical content writer. "
                "Your objective is to ingest the raw research report generated by Analisa and transform it "
                "into a cohesive, engaging narrative draft. You must seamlessly anchor, contextualize, and "
                "integrate natural links back to the user's specified target website. Maintain an authoritative "
                "yet highly engaging editorial voice. Focus heavily on structural flow, paragraph transitions, "
                "and compelling hooks, delivering a complete publication-ready draft outline."
            ),
            "agent_3": (
                "You are Checky, a meticulous quality control specialist and final layout editor. "
                "Your objective is to review the draft text compiled by Writus. You are responsible for enforcing "
                "strict grammatical excellence, ensuring flawless stylistic flow, checking that references to "
                "the target website look organic, and applying clean structural formatting. Your absolute final "
                "output must be delivered exclusively as perfectly formatted, semantic Markdown, free of any "
                "conversational meta-commentary or introductory conversational filler."
            )
        }
    else:
        prompts = {
            "agent_1": (
                "You are the Strategic Mapping Layer Analyst. Your role is to scrutinize the raw data schema "
                "of an uploaded source dataset and map it field-by-field against a rigorous target database schema. "
                "Identify datatype mismatches, naming variances, structural gaps, and potential serialization leaks. "
                "Output a comprehensive, deterministic mapping matrix blueprint detailing exactly how each source "
                "attribute transforms to fit the destination requirements perfectly."
            ),
            "agent_2": (
                "You are a Deterministic Software Architecture Execution Node. Your role is to take the mapping matrix "
                "blueprint from Agent 1 and generate a robust, self-contained Python data transformation script. "
                "The code must use standard libraries (like the built-in csv module), handle missing or corrupt input "
                "records gracefully, execute explicit type casting, and isolate the core application domain "
                "as a functional Anti-Corruption Layer protection interface."
            ),
            "agent_3": (
                "You are an Automated Quality Gate and Syntax Validation Node. Your role is to perform a rigorous "
                "code review on the script generated by Agent 2. Inspect the script for syntax correctness, type safety, "
                "boundary-condition vulnerabilities, and structural leaks. Polish the code formatting, and present the "
                "final, validated, production-ready script wrapped inside clean Markdown code blocks accompanied by a "
                "brief architectural stability summary."
            )
        }

    # 3. Layer specific variations over the defaults if present
    if load_task_id:
        try:
            past_task = AgentTask.objects.get(id=load_task_id)
            config_context = past_task.config_data
            prompts["agent_1"] = config_context.get("prompt_agent_1", prompts["agent_1"])
            prompts["agent_2"] = config_context.get("prompt_agent_2", prompts["agent_2"])
            prompts["agent_3"] = config_context.get("prompt_agent_3", prompts["agent_3"])
        except AgentTask.DoesNotExist:
            pass

    elif template_id:
        try:
            tmpl = PromptTemplate.objects.get(id=template_id)
            payload = json.loads(tmpl.system_prompt)
            prompts["agent_1"] = payload.get("agent_1", prompts["agent_1"])
            prompts["agent_2"] = payload.get("agent_2", prompts["agent_2"])
            prompts["agent_3"] = payload.get("agent_3", prompts["agent_3"])
        except (PromptTemplate.DoesNotExist, json.JSONDecodeError):
            pass

    # 4. Handle Form Submissions (POST)
    if request.method == 'POST':
        mode = request.POST.get('mode', mode)
        
        agent_1_text = request.POST.get('prompt_agent_1', '').strip()
        agent_2_text = request.POST.get('prompt_agent_2', '').strip()
        agent_3_text = request.POST.get('prompt_agent_3', '').strip()

        packed_config = {
            "model_agent_1": request.POST.get('model_agent_1'),
            "model_agent_2": request.POST.get('model_agent_2'),
            "model_agent_3": request.POST.get('model_agent_3'),
            "prompt_agent_1": agent_1_text,
            "prompt_agent_2": agent_2_text,
            "prompt_agent_3": agent_3_text,
        }
        
        if mode == 'ACLGENERATOR':
            packed_config["target_schema"] = request.POST.get('target_schema', '')
            if 'raw_csv' in request.FILES:
                csv_file = request.FILES['raw_csv']
                fs = FileSystemStorage(location='raw_uploads/')
                filename = fs.save(csv_file.name, csv_file)
                packed_config["uploaded_csv_path"] = os.path.join('raw_uploads/', filename)
            else:
                packed_config["uploaded_csv_path"] = config_context.get("uploaded_csv_path", "")
        else:
            packed_config["topic_brief"] = request.POST.get('topic_brief', '')

        new_task = AgentTask.objects.create(
            mode=mode,
            status='PENDING',
            config_data=packed_config
        )
        
        # --- THREAD HAND-OFF: Redirect immediately, run in background ---
        execution_thread = threading.Thread(
            target=execute_agent_task, 
            args=(new_task.id,)
        )
        execution_thread.start()
        
        # Browser flies to the execution page instantly!
        return redirect(f'/execution/{new_task.id}/')

    # 5. Fallback Page Render for GET requests (Fixes the ValueError)
    context = {
        'mode': mode,
        'saved_templates': saved_templates,
        'selected_template_id': template_id,
        'prompts': prompts,
        'config': config_context
    }
    return render(request, 'config_form.html', context)

def execution_page_view(request, task_id):
    """Step 3: Real-Time Telemetry Pipeline Screen Rendering"""
    task = get_object_or_404(AgentTask, id=task_id)
    return render(request, 'execution.html', {'task': task})

def get_task_logs_api(request, task_id):
    """Live Telemetry Log Stream Feed Polling Endpoint"""
    task = get_object_or_404(AgentTask, id=task_id)
    return JsonResponse({
        "status": task.status,
        "logs": task.config_data.get("execution_logs", []),
        "artifact": task.config_data.get("final_artifact", "") if task.status == "SUCCESS" else ""
    })

def dashboard_view(request):
    """Task Control Center History Grid Layout"""
    tasks = AgentTask.objects.all().order_by('-created_at')
    return render(request, 'dashboard.html', {'tasks': tasks})

# Append to web/views.py

def edit_config_view(request, task_id):
    """Redirects to config form with historical context loaded for editing"""
    past_task = get_object_or_404(AgentTask, id=task_id)
    return redirect(f'/configure/?mode={past_task.mode}&load_task_id={past_task.id}')

def rerun_task_view(request, task_id):
    """Instantly clones the configuration and triggers the orchestrator execution"""
    past_task = get_object_or_404(AgentTask, id=task_id)
    new_task = AgentTask.objects.create(
        mode=past_task.mode,
        status='PENDING',
        config_data=past_task.config_data.copy()
    )
    # Clear out old execution metrics/logs for the new run window
    if "execution_logs" in new_task.config_data:
        new_task.config_data["execution_logs"] = []
    if "final_artifact" in new_task.config_data:
        del new_task.config_data["final_artifact"]
    new_task.save()

    # --- THREAD HAND-OFF: Redirect immediately, run in background ---
    execution_thread = threading.Thread(
        target=execute_agent_task, 
        args=(new_task.id,)
    )
    execution_thread.start()

    return redirect(f'/execution/{new_task.id}/')

def duplicate_task_view(request, task_id):
    """Redirects to form configuration with historical data replicated as a clean template"""
    past_task = get_object_or_404(AgentTask, id=task_id)
    return redirect(f'/configure/?mode={past_task.mode}&load_task_id={past_task.id}')

def delete_task_view(request, task_id):
    """Permanently removes task execution records from the database state"""
    task = get_object_or_404(AgentTask, id=task_id)
    task.delete()
    return redirect('dashboard')

def task_status_api(request, task_id):
    """Fallback status API endpoint to support legacy naming variations in templates"""
    task = get_object_or_404(AgentTask, id=task_id)
    return JsonResponse({
        "status": task.status,
        "logs": "\n".join(task.config_data.get("execution_logs", [])) 
                if isinstance(task.config_data.get("execution_logs"), list) 
                else task.config_data.get("execution_logs", "")
    })

@require_POST
def delete_task_view(request, task_id):
    """Permanently removes task execution records from the database state"""
    task = get_object_or_404(AgentTask, id=task_id)
    task.delete()
    return redirect('dashboard')